# Site settings
title: Uddyami's Profile
email: uddyamiagrawal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn to use GitHub pages with Wheelhouse.io and Patchwork!
baseurl: "/patchwork-gh-pages-24"
url: "http://uddyami.github.io"
twitter_username: uddyami
github_username:  uddyami
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
