# Site settings
title: Uddyami's Profile
email: uddyamiagrawal@gmail.com
description: Brain runs faster than fingers!
baseurl: ""
url: ""
twitter_username: uddyami
github_username:  uddyami
linkedin_url:  uddyami-agrawal-b9062414
permalink: /blog/:year/:title/

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index

theme: jekyll-theme-architect