# Site settings
title: Uddyami's Profile
email: uddyamiagrawal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn to use GitHub pages with Wheelhouse.io and Patchwork!
baseurl: ""
url: "http://uddyami.github.io"
twitter_username: uddyami
github_username:  uddyami
permalink: /blog/:year/:title/

[Linkedin] (https://www.linkedin.com/in/uddyami-agrawal-b9062414)

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
